### ISSUE TITLE
HiDPI screens not supported

### ISSUE THREAD

**Issue by Lucretia** [SubhadeepJasu/Ensembles#49]
The UI doesn't scale properly, the fonts on the buttons are tiny, try scaling your 1080p screen down 4 times to get an idea. The image in the middle doesn't scale, text is unreadable.

**Comment by SubhadeepJasu** [comment]
Related to #24

**Comment by SubhadeepJasu** [comment]
Progress on these:
Higher UI scaling
![Screenshot from 2021-11-19 16-46-21](https://user-images.githubusercontent.com/20795161/142614638-8dc64c13-273a-467f-957c-c6efea1ffd3b.png)

Normal Scaling (with respect to my laptop)
![Screenshot from 2021-11-19 16-47-18](https://user-images.githubusercontent.com/20795161/142614651-65a4cc17-67d2-4f8f-89cb-566d0bba5958.png)

**Comment by Lucretia** [comment]
The text on the buttons on the right are still too small on hidpi. I'd move the "led" to the left or the right and let the text fill the button, or put it in the prefs.

**Comment by SubhadeepJasu** [comment]
I'll try enlarging the text a bit more. Looks like there is room. If it's still too small (after we have seen the app in actual scenario), I'll move the Led thing to the left.

**Comment by SubhadeepJasu** [comment]
@Lucretia  How does the new latest version look on your screen?

**Comment by Lucretia** [comment]
No idea, I can't get it to run.

**Comment by SubhadeepJasu** [comment]
Oh no! The one from appcenter?

**Comment by Lucretia** [comment]
I've tried the flatpak from here and I've created a gentoo ebuild for it locally, neither work. Running the built one, I get the following:
```
$ com.github.subhadeepjasu.ensembles `whoami`
Failed to register: Timeout was reached
```

And running the flatpak:

```
$ /usr/bin/flatpak run --branch=master --arch=x86_64 --command=com.github.subhadeepjasu.ensembles --file-forwarding com.github.subhadeepjasu.ensembles `whoami`
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
F: Can't get document portal mount path

(com.github.subhadeepjasu.ensembles:3): GLib-GIO-WARNING **: 12:14:09.758: Can't find module 'dconf' specified in GSETTINGS_BACKEND
Gtk-Message: 12:14:09.763: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:14:09.763: Failed to load module "appmenu-gtk-module"
Failed to register: Timeout was reached
```

**Comment by SubhadeepJasu** [comment]
How's the size of text in those buttons?

**Comment by Lucretia** [comment]
Yeah, they're readable now.

**Comment by SubhadeepJasu** [comment]
@Lucretia I just released an alpha today. Can you please once confirm that the layout issue is fixed on your end?

**Comment by SubhadeepJasu** [comment]
Closing as this issue seems to have been fixed.
