### ISSUE TITLE
Error while compiling from source

### ISSUE THREAD

**Issue by Suzie97** [SubhadeepJasu/Ensembles#5]
Hey, I wanted to test the app and add some features if I can. But I get an error while compiling.

![Screenshot from 2021-07-03 01-33-40](https://user-images.githubusercontent.com/68198116/124323370-d6344e80-db9e-11eb-90f5-e6ba729cf35f.png)

Can you help?

**Comment by SubhadeepJasu** [comment]
Are you using fluidsynth 2.2.1? It doesn't ship with elementary, so you may need to build it from source.

**Comment by SubhadeepJasu** [comment]
I would recommend pulling from master one more time and using the flatpak build. That will install all dependencies automatically. I have updated the README to include steps to do that. You will need flatpak-builder.

**Comment by Suzie97** [comment]
> 
> 
> Are you using fluidsynth 2.2.1? It doesn't ship with elementary, so you may need to build it from source.

can you tell the package name? I installed fluisynth but it installed a gui app

**Comment by SubhadeepJasu** [comment]
Its this: https://github.com/FluidSynth/fluidsynth . You need to remove any existing fluidsynth installation. The one that elementary ships with is very old. Before doing `sudo make install` use `cmake -DLIB_INSTALL_DIR=/usr/lib ..`. That should do a proper installation of fluidsynth.

**Comment by SubhadeepJasu** [comment]
UPDATE: libfluidsynth-dev is available in elementary OS 6. You can install both libfluidsynth-dev and libportmidi-dev using

```
sudo apt install libfluidsynth-dev
```
and 
```
sudo apt install libportmidi-dev
```

**Comment by Suzie97** [comment]
> UPDATE: libfluidsynth-dev is available in elementary OS 6. You can install both libfluidsynth-dev and libportmidi-dev using
> 
> ```
> sudo apt install libfluidsynth-dev
> ```
> 
> and
> 
> ```
> sudo apt install libportmidi-dev
> ```

I tried installing these packages, but they don't work.

**Comment by Suzie97** [comment]
I tried building fluidsynth from source, the app compiled too, without errors.

But this happens with me and I can't solve it.
https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#note

As for the flatpak, there is something wrong with the GNOME runtime in my machine. Doesn't get installed. I'll see if I can solve the issues. Thank you for your help. 

I'm closing this issue as the fault is in my system and not the app.

**Comment by SubhadeepJasu** [comment]
I switched to io.elementary runtime recently. So if you have eOS, that's an option.

**Comment by Suzie97** [comment]
> I switched to io.elementary runtime recently. So if you have eOS 6, that's an option.

oh great, I'll try it soon 😀️
