### ISSUE TITLE
Implementation of preset settings for popular MIDI controllers

### ISSUE THREAD

**Issue by shayakbanerjee99** [SubhadeepJasu/Ensembles#50]
Hi!

I wanted to suggest that preset mappings for some of the most popular MIDI controllers can be added or at least there could be an option where the different mappings could be saved(exported) and loaded. So that when one person has done the config, others can use it without having to go through the process.

**Comment by SubhadeepJasu** [comment]
Definitely possible. Great idea!

**Comment by SubhadeepJasu** [comment]
Feature Implemented
