### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by flxzt** [SubhadeepJasu/Ensembles#71]
Currently ensembles is creating `~/Documents/Ensembles` for its configuration files.
I think it should follow the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) and place its configuration wherever XDG_CONFIG_HOME is pointing to.

Glib even has the function [get_user_config_dir](https://docs.gtk.org/glib/func.get_user_config_dir.html) for retreiving the path.

**Comment by SubhadeepJasu** [comment]
It doesn't store configurations there. That folder stores user files like styles, recordings, display themes, etc.

**Comment by flxzt** [comment]
then maybe XDG_DATA_HOME or XDG_DOCUMENTS_DIR ?

**Comment by SubhadeepJasu** [comment]
yeah that I should do, unless its already like that in the code. Also just found that, it also stores input presets which are configuration files, which I will definitely store in XDG_CONFIG_HOME. Thanks for bringing it up.

**Comment by SubhadeepJasu** [comment]
Slight change: I can't use XDG_DATA_HOME because that's for user data which is analogous to installed data in /usr/share. Also I don't see anything like XDG_DOCUMENT_DIR in the XDG Base Directory specification. I remove the document part from the path, so its just HOME. Configs will be stored in a subdirectory under XDG_CONFIG_HOME.

**Comment by flxzt** [comment]
There is though, its not in the linked spec for the base-dirs, but there is [this](https://wiki.archlinux.org/title/XDG_user_directories) which specifies exactly what you want, "XDG_DOCUMENT_DIR", and is used by all main distributions.

**Comment by SubhadeepJasu** [comment]
That's planned as well. I am just setting something as default for now.

**Comment by flxzt** [comment]
Ok, sounds good :) This would be the glib function for easy retreival of the dir: https://docs.gtk.org/glib/func.get_user_special_dir.html

**Comment by SubhadeepJasu** [comment]
That did it. Thanks for the help :)

**Comment by SubhadeepJasu** [comment]
![Screenshot from 2022-03-20 12-28-07](https://user-images.githubusercontent.com/20795161/159151888-2b8fbd2b-2488-47f2-b30d-4d4df620364d.png)
![Screenshot from 2022-03-20 12-29-36](https://user-images.githubusercontent.com/20795161/159151889-3690cbf0-bf76-40ea-ac90-5e87ba370b2c.png)
