### ISSUE TITLE
Feature Request: Add Real Fill-in, and Break support

### ISSUE THREAD

**Issue by wepache** [SubhadeepJasu/Ensembles#79]
Currently the Fill-In Buttons just work as a way to change Variations, but there are no actual fills. It would be great if it supported Fill-ins. Also right now the Break button only stops the music till the next bar down beat. It would be great if instead of stopping, it supported an actual drum break, like most Yahama Arrangers, and Korg Arrangers support.

**Comment by SubhadeepJasu** [comment]
I see what you mean. I'll need to change the specification a bit to support that kind of break, but that would be nice ultimately. As for fills, it does support actual fills. You just have to press the same variation button that you are at. It's more of a CASIO method than Yamaha's. So if  I want to add a fill between A and B. I do this:

- I am in variation A
- I click the A button again (This triggers the fill)
- I click B before the measure ends. (So right after the fill it goes to B smoothly)

**Comment by SubhadeepJasu** [comment]
Here I am going from C -> D in one of the new styles
https://user-images.githubusercontent.com/20795161/168457081-310a438f-ba42-4efb-9b83-a14d685ff7c7.mp4

**Comment by wepache** [comment]
Awesome! That's actually exactly what I was trying to do. That should suffice for now. The break is not really important since I am able to do fills through other means. I am sure the break stopping will be useful to many people.

**Comment by SubhadeepJasu** [comment]
It's useful in a couple of songs where you need all the music to stop and have to come in the next measure. Adds a certain kind of unique flare.
