### ISSUE TITLE
Recommend Odin SDK as main compiling method

### ISSUE THREAD

**Issue by hanaral** [SubhadeepJasu/Ensembles#8]
This should reinforce flatpak as the main way to get the app, therefore focusing all the testing on the only format the app will be available in the AppCenter. It would also probably mean less hassle with setting up build dependencies and people complaining about X dependency not being available in the LTS repos :^)

**Comment by SubhadeepJasu** [comment]
I have updated the readme to put flatpak build at first and meson as a fallback.  I haven't mentioned Odin, but I have mentioned elementary platform and sdk as flatpak requirements.

**Comment by SubhadeepJasu** [comment]
Closing as it has been fixed. Feel free to let me know if I missed anything.
