### ISSUE TITLE
Feature Request: Ability to use multiple midi keyboards for specific purposes

### ISSUE THREAD

**Issue by wepache** [SubhadeepJasu/Ensembles#80]
It would be great if I could set 1 midi keyboard specifically for changing chords, and another one for right hand playing.

**Comment by SubhadeepJasu** [comment]
This is a good idea. I'll also have to add a related issue where it support multiple MIDI inputs simultaneously. The differentiation between the keyboards can be done by selecting MIDI channels in the keyboards, so channel 1 is always going to support chords and right hand, but if higher channels are present then also divide the virtual keyboard in all octaves among them.

**Comment by SubhadeepJasu** [comment]
Implemented
