### ISSUE TITLE
Release flatpak bundle for testers under tagged releases

### ISSUE THREAD

**Issue by hanaral** [SubhadeepJasu/Ensembles#9]
Cassidy-James started doing this with his app Dippi, it really speeds up testing as users can install with a couple of clicks, an easily uninstall. 
Maybe in the future there could even be a 'BETA' banner in-app and a badged app icon to make sure users know that it's just a snapshot.

**Comment by SubhadeepJasu** [comment]
Sure. I gotta check how to do that.

**Comment by SubhadeepJasu** [comment]
Done !
